eventus/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include
from django.views.static import serve
from comum.views import InscreverView
from eventos.views.pagamento import pagseguro_notification
import cbvadmin


urlpatterns = [
    url(r'^admin/', cbvadmin.site.urls),
    url(r'^accounts/register/$', InscreverView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^preferences/', include('dynamic_preferences.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^attachments/', include('attachments.urls',
                                  namespace='attachments')),
    url(r'^pagamento/paypal/', include('paypal.standard.ipn.urls')),
    url(r'^pagamento/pagseguro/', pagseguro_notification),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            serve, {'document_root': settings.MEDIA_ROOT})
    ]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

oficinas/models.py
from djchoices import DjangoChoices, ChoiceItem
from django.db import models
from comum.models import Usuario
from eventos.models import Inscricao


class Oficina(models.Model):
    class Situacao(DjangoChoices):
        Pendente = ChoiceItem(0)
        Aprovado = ChoiceItem(1)
        Reprovado = ChoiceItem(2)

    nome = models.CharField(max_length=100)
    ministrante = models.ForeignKey(Usuario, on_delete=models.CASCADE,
                                    related_name='oficinas')
    arquivo = models.FileField(upload_to='oficinas', blank=False)
    vagas = models.IntegerField(default=0)
    situacao = models.IntegerField(choices=Situacao.choices,
                                   verbose_name='situação',
                                   default=0, editable=False)
    inscricoes = models.ManyToManyField(Inscricao, related_name='oficinas',
                                        blank=True, editable=False)

    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    def vagas_restantes(self):
        return self.vagas - self.inscricoes.count()


class MesaRedonda(models.Model):
    class Situacao(DjangoChoices):
        Pendente = ChoiceItem(0)
        Aprovado = ChoiceItem(1)
        Reprovado = ChoiceItem(2)

    nome = models.CharField(max_length=100)
    ministrante = models.ForeignKey(Usuario, on_delete=models.CASCADE,
                                    related_name='mesasredondas')
    arquivo = models.FileField(upload_to='mesas_redondas', blank=False)
    situacao = models.IntegerField(choices=Situacao.choices,
                                   verbose_name='situação',
                                   default=0, editable=False)
    inscricoes = models.ManyToManyField(Inscricao, blank=True, editable=False,
                                        related_name='mesasredondas')

    class Meta:
        ordering = ('nome',)
        verbose_name = 'mesa-redonda'
        verbose_name_plural = 'mesas-redondas'

    def __str__(self):
        return self.nome


class Seminario(models.Model):
    class Situacao(DjangoChoices):
        Pendente = ChoiceItem(0)
        Aprovado = ChoiceItem(1)
        Reprovado = ChoiceItem(2)

    nome = models.CharField(max_length=100)
    ministrante = models.ForeignKey(Usuario, on_delete=models.CASCADE,
                                    related_name='seminarios')
    arquivo = models.FileField(upload_to='seminarios', blank=False)
    vagas = models.IntegerField(default=0)
    situacao = models.IntegerField(choices=Situacao.choices,
                                   verbose_name='situação',
                                   default=0, editable=False)
    inscricoes = models.ManyToManyField(Inscricao, related_name='seminarios',
                                        blank=True, editable=False)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'seminário temático'
        verbose_name_plural = 'seminários temáticos'

    def __str__(self):
        return self.nome

    def vagas_restantes(self):
        return self.vagas - self.inscricoes.count()


class Livro(models.Model):
    class Situacao(DjangoChoices):
        Pendente = ChoiceItem(0)
        Aprovado = ChoiceItem(1)
        Reprovado = ChoiceItem(2)

    titulo = models.CharField(max_length=100)
    editora = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100, verbose_name='ISBN')
    ano = models.IntegerField()
    autores = models.CharField(max_length=100)
    biografia = models.TextField()
    resumo = models.TextField()
    palavras_chave = models.CharField(max_length=100)
    paginas = models.IntegerField()
    preco = models.DecimalField(max_digits=8, decimal_places=2,
                                verbose_name='preço')
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=100)
    email = models.CharField(max_length=100, verbose_name='e-mail')
    capa = models.FileField(upload_to='livros', blank=False, null=False)
    situacao = models.IntegerField(choices=Situacao.choices,
                                   verbose_name='situação',
                                   default=0, editable=False)

    def __str__(self):
        return self.titulo

oficinas/forms.py
from django import forms
from django.conf import settings
from django.forms import ValidationError
from comum.utils.file_upload import UploadMaxSizeMixin, humanbytes
from dynamic_preferences.registries import global_preferences_registry
from eventos.models import Inscricao
from .models import Oficina, MesaRedonda, Seminario


class OficinaSubmeterForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = Oficina
        exclude = ('local', 'tipo', 'ministrante', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome da oficina'


class OficinaChangeForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = Oficina
        exclude = ('tipo', 'ministrante', 'arquivo', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome da oficina'


class OficinaInscricaoForm(forms.ModelForm):
    atividades = forms.ModelMultipleChoiceField(
        queryset=Oficina.objects.filter(situacao=Oficina.Situacao.Aprovado),
        required=False)

    class Meta:
        model = Inscricao
        fields = ['atividades']

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            instance = kwargs.get('instance')
            initial = kwargs.setdefault('initial', {})
            initial['atividades'] = instance.oficinas.values_list(
                'pk', flat=True)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        prefs = global_preferences_registry.manager()

        if ('atividades' in cleaned_data and
                len(cleaned_data['atividades']) >
                prefs['oficinas__inscricao_max']):
            raise ValidationError(
                'Você deve selecionar no máximo %d oficina(s)' %
                prefs['oficinas__inscricao_max'])
        return cleaned_data

    def save(self, *args, **kwargs):
        self.instance.oficinas.clear()
        for o in Oficina.objects.filter(
                pk__in=self.cleaned_data['atividades']):
            o.inscricoes.add(self.instance)


class SubmeterMesaRedondaForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = MesaRedonda
        exclude = ('local', 'tipo', 'ministrante', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome da mesa redonda'


class ChangeMesaRedondaForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = MesaRedonda
        exclude = ('tipo', 'ministrante', 'arquivo', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome da mesa redonda'


class MesaRedondaInscricaoForm(forms.ModelForm):
    atividades = forms.ModelMultipleChoiceField(
        queryset=MesaRedonda.objects.filter(
            situacao=MesaRedonda.Situacao.Aprovado), required=False)

    class Meta:
        model = Inscricao
        fields = ['atividades']

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            instance = kwargs.get('instance')
            initial = kwargs.setdefault('initial', {})
            initial['atividades'] = instance.mesasredondas.values_list(
                'pk', flat=True)
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.mesasredondas.clear()
        for o in MesaRedonda.objects.filter(
                pk__in=self.cleaned_data['atividades']):
            o.inscricoes.add(self.instance)


class SeminarioSubmeterForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = Seminario
        exclude = ('local', 'tipo', 'ministrante', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome dó seminário temático'


class SeminarioChangeForm(UploadMaxSizeMixin, forms.ModelForm):
    class Meta:
        model = Seminario
        exclude = ('tipo', 'ministrante', 'arquivo', 'inscricoes')
        help_texts = {
            'arquivo': 'Tamanho maximo de %s' % humanbytes(settings.FILE_UPLOAD_MAX_SIZE)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].label = 'Nome da oficina'


class SeminarioInscricaoForm(forms.ModelForm):
    atividades = forms.ModelMultipleChoiceField(
        queryset=Seminario.objects.filter(
            situacao=Seminario.Situacao.Aprovado),
        required=False)

    class Meta:
        model = Inscricao
        fields = ['atividades']

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            instance = kwargs.get('instance')
            initial = kwargs.setdefault('initial', {})
            initial['atividades'] = instance.seminarios.values_list(
                'pk', flat=True)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        prefs = global_preferences_registry.manager()

        if ('atividades' in cleaned_data and
                len(cleaned_data['atividades']) >
                prefs['seminarios__inscricao_max']):
            raise ValidationError(
                'Você deve selecionar no máximo %d seminários temáticos(s)' %
                prefs['seminarios__inscricao_max'])
        return cleaned_data

    def save(self, *args, **kwargs):
        self.instance.seminarios.clear()
        for o in Seminario.objects.filter(
                pk__in=self.cleaned_data['atividades']):
            o.inscricoes.add(self.instance)

oficinas/views.py
from django.shortcuts import redirect, Http404
from django.urls import reverse
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages
from cbvadmin.views.edit import AddView, EditView
from comum.views import BasicView
from eventos.models import Inscricao


class SubmeterAtividadeView(AddView):
    default_template = 'oficinas/atividade_submeter.html'
    raise_exception = False

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.ministrante = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class AvaliarAtividadeView(SingleObjectMixin, BasicView):
    def get(self, request, *args, **kwargs):
        success_url = self.get_success_url()
        return redirect(success_url)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        avaliacao = request.POST.get('situacao')
        self.object.situacao = avaliacao
        self.object.save()
        messages.success(request, 'Atividade "%s" avaliada' %
                         self.object.nome)
        return redirect(success_url)


class InscricaoAtividadeView(EditView):
    default_template = 'oficinas/atividade_inscricao.html'
    success_message = 'Inscrições salvas'
    permission_required = []

    def get_form_class(self):
        return self.admin.inscricao_form_class

    def get_object(self):
        try:
            return self.request.user.inscricao
        except Inscricao.DoesNotExist:
            raise Http404

    def get_success_url(self):
        return reverse(self.admin.urls['inscricao'])

oficinas/templates/cbvadmin/oficinas/atividade_inscricao.html
{% extends 'cbvadmin/semantic-ui/base_site.html' %}

{% block title %}Inscrever-se em {{ view.admin.model_opts.verbose_name_plural }}{% endblock %}

{% block content %}
{% if form.non_field_errors %}
<div class="ui error message">
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
</div>
{% else %}
{% if view.admin.max_inscriccoes %}
<div class="ui warning message">
  Você deve selecionar no máximo {{ view.admin.max_inscriccoes }}
  {% if view.admin.max_inscriccoes > 1 %}{{ view.admin.model_opts.verbose_name_plural }}{% else %}{{ view.admin.model_opts.verbose_name }}{% endif %}  
</div>
{% endif %}
{% endif %}
<form method="post" class="ui form">
  {% csrf_token %}
  <button type="submit" class="ui primary button">Salvar</button>
  <table class="ui table">
    <thead>
      <tr>
        <th></th>
        <th>Oficina</th>
       
        {% if view.admin.limitar_vagas %}
        <th>Vagas</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
    {% for choice in form.atividades.field.queryset %}
      <tr>
        <td class="collapsing">
          {% spaceless %}
          {% if choice.pk in form.atividades.value or choice.pk|slugify in form.atividades.value %}
          <div class="ui fitted toggle checkbox">
            <input name="atividades" id="id_oficinas_{{ choice.pk }}" value="{{ choice.pk }}" type="checkbox" checked="checked">
            <label></label>
          </div>
          {% else %}
          {% if choice.vagas_restantes > 0 or not view.admin.limitar_vagas %}
          <div class="ui fitted toggle checkbox">
            <input name="atividades" id="id_oficinas_{{ choice.pk }}" value="{{ choice.pk }}" type="checkbox">
            <label></label>
          </div>
          {% endif %}
          {% endif %}
          {% endspaceless %}
        </td>
        <td>{{ choice.nome }}</td>
        
        {% if view.admin.limitar_vagas %}
        <td {% if choice.vagas_restantes == 0%} class="negative"{% endif %}>{{ choice.vagas_restantes }}</td>
        {% endif %}
      </tr>
    {% empty %}
    <tr>
      <td colspan="{{ view.admin.limitar_vagas|yesno:'4,3' }}" class="center aligned">Nenhum {{ view.admin.model_opts.verbose_name }} disponível</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  <button type="submit" class="ui primary button">Salvar</button>
</form>
{% endblock %}

oficinas/templates/cbvadmin/oficinas/atividade_submeter.html
{% extends 'cbvadmin/semantic-ui/change_form.html' %}

{% block title %}Submeter {{ view.admin.model_opts.verbose_name }}{% endblock %}

oficinas/templates/cbvadmin/oficinas/livro_detail.html
{% extends 'cbvadmin/oficinas/oficina_detail.html' %}

{% block details %}
<table class="ui definition unstackable table">
  <tr>
    <td>Situação</td>
    <td>
      {% if object.situacao == 1 %}
      <div class="ui green label">
        {{ object.get_situacao_display }}
      </div>
      {% elif object.situacao == 2 %}
      <div class="ui orange label">
        {{ object.get_situacao_display }}
      </div>
      {% else %}
      <div class="ui grey label">
        {{ object.get_situacao_display }}
      </div>
      {% endif %}
    </td>
  </tr>
  <tr><td>Título</td><td>{{ object.titulo }}</td></tr>
  <tr><td>Editora</td><td>{{ object.editora }}</td></tr>
  <tr><td>ISBN</td><td>{{ object.isbn }}</td></tr>
  <tr><td>Ano</td><td>{{ object.ano }}</td></tr>
  <tr><td>Autores</td><td>{{ object.autores }}</td></tr>
  <tr><td>Biografia</td><td>{{ object.biografia }}</td></tr>
  <tr><td>Resumo</td><td>{{ object.resumo }}</td></tr>
  <tr><td>Palavras chave</td><td>{{ object.palavras_chave }}</td></tr>
  <tr><td>Páginas</td><td>{{ object.paginas }}</td></tr>
  <tr><td>Preço</td><td>{{ object.preco }}</td></tr>
  <tr><td>Nome</td><td>{{ object.nome }}</td></tr>
  <tr><td>Telefone</td><td>{{ object.telefone }}</td></tr>
  <tr><td>E-mail</td><td>{{ object.email }}</td></tr>
  <tr>
    <td>Capa</td>
    <td><img class="ui small image" src="{{ object.capa.url }}" alt="Capa do livro"/></a></td>
  </tr>
</table>
{% endblock %}

oficinas/templates/cbvadmin/oficinas/mesaredonda_detail.html
{% extends 'cbvadmin/oficinas/oficina_detail.html' %}

oficinas/templates/cbvadmin/oficinas/oficina_detail.html
{% extends 'cbvadmin/semantic-ui/base_site.html' %}
{% load i18n %}

{% block title %}Visualizar {{ view.admin.model_opts.verbose_name|capfirst }}{% endblock %}


{% block content %}
{% block actions %}
<div class="ui mobile only fluid">
  {% if admin.urls.edit %}
  <div class="ui two fluid buttons">
    <div class="ui labeled icon top left floating pointing dropdown positive avaliar 
    button">
      <i class="thumbs up icon"></i>
      Aprovar
      <form class="menu" method="post" action="{% url admin.urls.avaliar object.pk %}">
        {% csrf_token %}
        <input type="hidden" name="situacao" value="1">
        <div class="item"><button class="ui small button">Confirmar</button></div>
      </form>
    </div>
    <div class="ui labeled icon top right floating pointing dropdown negative avaliar 
    button">
      <i class="thumbs down icon"></i>
      Reprovar
      <form class="menu" method="post" action="{% url admin.urls.avaliar object.pk %}">
        {% csrf_token %}
        <input type="hidden" name="situacao" value="2">
        <div class="item"><button class="ui small button">Confirmar</button></div>
      </form>
    </div>
  </div>
  <a href="{% url admin.urls.edit object.pk %}" class="ui primary fluid button">
    <i class="plus icon"></i> Alterar
  </a>
  {% endif %}
</div>
<div class="ui secondary mobile hidden menu">
  <div class="ui right item">
    {% if admin.urls.edit %}
    <div class="ui buttons">
      <div class="ui labeled icon floating pointing dropdown positive avaliar 
      button">
        <i class="thumbs up icon"></i>
        Aprovar
        <form class="menu" method="post" action="{% url admin.urls.avaliar object.pk %}">
          {% csrf_token %}
          <input type="hidden" name="situacao" value="1">
          <div class="item"><button class="ui small button">Confirmar</button></div>
        </form>
      </div>
      <div class="ui labeled icon floating pointing dropdown negative avaliar 
      button">
        <i class="thumbs down icon"></i>
        Reprovar
        <form class="menu" method="post" action="{% url admin.urls.avaliar object.pk %}">
          {% csrf_token %}
          <input type="hidden" name="situacao" value="2">
          <div class="item"><button class="ui small button">Confirmar</button></div>
        </form>
      </div>
    </div>
    <a href="{% url admin.urls.edit object.pk %}" class="ui primary button">
      <i class="pencil icon"></i> Alterar
    </a>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block details %}
<table class="ui definition unstackable table">
  <tr>
    <td>Nome</td>
    <td>{{ object.nome }}</td>
  </tr>
  <tr>
    <td>Ministrante</td>
    <td>{{ object.ministrante }}</td>
  </tr>
  <tr>
    <td>Arquivo</td><td><a href="{{ object.arquivo.url }}">{{ object.arquivo }}</a></td>
  </tr>
  <tr>
    <td>Aprovado</td>
    <td>
      {% if object.situacao == 1 %}
      <div class="ui green label">
        {{ object.get_situacao_display }}
      </div>
      {% elif object.situacao == 2 %}
      <div class="ui orange label">
        {{ object.get_situacao_display }}
      </div>
      {% else %}
      <div class="ui grey label">
        {{ object.get_situacao_display }}
      </div>
      {% endif %}
    </td>
  </tr>
</table>

<h2>Inscrições</h2>
<table class="ui compact table">
  <thead>
    <tr>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    {% for inscricao in object.inscricoes.all %}
    <tr>
      <td>{{ inscricao.usuario.nome_completo }}</td>
    </tr>
    {% empty %}
    <tr>
      <td>Nenhuma inscrição</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% endblock %}

{% block extrascript %}
{{ block.super }}
{{ form.media.js }}
<script type="text/javascript">
$('.avaliar.button').dropdown()
</script>
{% endblock %}

oficinas/templates/cbvadmin/oficinas/oficina_inscricao.html
{% extends 'cbvadmin/semantic-ui/base_site.html' %}

{% block title %}Inscrever-se em oficinas{% endblock %}

{% block content %}
{% if form.non_field_errors %}
<div class="ui error message">
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
</div>
{% else %}
<div class="ui warning message">
  Você deve selecionar no máximo {{ global_preferences.oficinas__inscricao_max }} oficina(s)
</div>
{% endif %}
<form method="post" class="ui form">
  {% csrf_token %}
  <button type="submit" class="ui primary button">Salvar</button>
  <table class="ui table">
    <thead>
      <tr>
        <th></th>
        <th>Oficina</th>
        <th>Ministrante</th>
        <th>Vagas</th>
      </tr>
    </thead>
    <tbody>
    {% for choice in form.oficinas.field.queryset %}
      <tr>
        <td class="collapsing">
          {% spaceless %}
          {% if choice.pk in form.oficinas.value or choice.pk|slugify in form.oficinas.value %}
          <div class="ui fitted toggle checkbox">
            <input name="oficinas" id="id_oficinas_{{ choice.pk }}" value="{{ choice.pk }}" type="checkbox" checked="checked">
            <label></label>
          </div>
          {% else %}
          {% if choice.vagas_restantes > 0 %}
          <div class="ui fitted toggle checkbox">
            <input name="oficinas" id="id_oficinas_{{ choice.pk }}" value="{{ choice.pk }}" type="checkbox">
            <label></label>
          </div>
          {% endif %}
          {% endif %}
          {% endspaceless %}
        </td>
        <td>{{ choice.nome }}</td>
        <td>{{ choice.ministrante }}</td>
        <td {% if choice.vagas_restantes == 0%} class="negative"{% endif %}>{{ choice.vagas_restantes }}</td>
      </tr>
    {% empty %}
    <tr>
      <td colspan="3">Nenhuma oficina disponível</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  <button type="submit" class="ui primary button">Salvar</button>
</form>
{% endblock %}

oficinas/templates/cbvadmin/oficinas/seminario_detail.html
{% extends 'cbvadmin/oficinas/oficina_detail.html' %}